<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>myscript</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#nestedtermsexternal</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#nestedterms</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#terms</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#punctuations</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#codes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.number-sign.myscript</string>
            <key>match</key>
            <string>\# .+</string>
          </dict>
        </array>
      </dict>
      <key>codes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.language.myscript</string>
            <key>match</key>
            <string>\#\w+</string>
          </dict>
        </array>
      </dict>
      <key>nestedtermsexternal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.language.myscript</string>
            <key>begin</key>
            <string>([a-z][a-z0-9]*(?:-[a-z0-9]+)*) </string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.myscript</string>
              </dict>
            </dict>
            <key>end</key>
            <string>[,]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#terms</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numbers</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#codes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>nestedterms</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>term.language.myscript</string>
            <key>begin</key>
            <string>([a-z][a-z0-9]*(?:-[a-z0-9]+)*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.myscript</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.myscript</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.myscript</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#terms</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numbers</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#codes</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>terms</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>term.language.myscript</string>
            <key>match</key>
            <string>([a-z][a-z0-9]*(?:-[a-z0-9]+)*)</string>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.integer.myscript</string>
            <key>match</key>
            <string>\d+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.myscript</string>
            <key>match</key>
            <string>\d+\.\d+</string>
          </dict>
        </array>
      </dict>
      <key>punctuations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.separator.parameter.myscript</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.curly.open.myscript</string>
            <key>match</key>
            <string>\{</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.curly.close.myscript</string>
            <key>match</key>
            <string>\}</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>name</key>
        <string>template.myscript</string>
        <key>begin</key>
        <string>\&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.myscript</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.myscript</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#codes</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.term.myscript</string>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.myscript</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.myscript</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#nestedterms</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#terms</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numbers</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuations</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#codes</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
            <key>match</key>
            <string>[^\#\{\}\&gt;]+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
            <key>match</key>
            <string>\#</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.jsl</string>
  </dict>
</plist>