<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsl</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
    <key>repository</key>
    <dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#model</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifiersNotInEntity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lambda-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal-signal</string>				
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(self|extends|model|abstract|import)\b</string>
					<key>name</key>
					<string>keyword.control.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?|:</string>
					<key>name</key>
					<string>keyword.control.ternary.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.control.jsl</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
					<key>name</key>
					<string>keyword.operator.comparison.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\-|\+|\*|\/|div|mod</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>not|and|or|implies</string>
					<key>name</key>
					<string>keyword.operator.logical.jsl</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(enum)\b</string>
					<key>name</key>
					<string>storage.types.class.jsl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(type )\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.type.typeDeclaration.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#primitives</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>						
					</array>
				</dict>
			</array>
		</dict>
		<key>model</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(model)\b </string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.model.modelDeclaration.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelname</string>
						</dict>					
					</array>
				</dict>
			</array>
		</dict>
		<key>modelname</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\w+)(::)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.namespaceName.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\w+</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.class.namespaceName.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
				</dict>
			</array>
		</dict>
		<key>import</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(import)\b </string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.import.importLibreries.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\w+)(::)</string>
							<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>support.class.namespaceName.jsl</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.jsl</string>
									</dict>
								</dict>
						</dict>
						<dict>
							<key>begin</key>
							<string>\w+</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>support.class.namespaceName.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>as</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(?=;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>\w+</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>support.variable.alliasName.jsl</string>
												</dict>
											</dict>
											<key>end</key>
											<string>(?=;)</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>primitives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(boolean|binary|string|numeric|date|time|timestamp)\b\s+(\w+)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.primitives.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.typeName.jsl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
					<dict>
						<key>begin</key>
						<string>\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.parameter.begin.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\))</string>
							<key>name</key>
							<string>meta.paramters.in.jsl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>(\w+|\w+-\w+)\s*=</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>variable.parameter.typeDeclaration.jsl</string>
										</dict>
									</dict>
								</dict>
								<dict>
									<key>include</key>
									<string>#literals</string>
								</dict>
							</array>
					</dict>
			</array>
		</dict>		
		<key>modifiersInEntity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(field|identifier|relation|derived|query)\b(\s+required)?\s+(\w+)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.typeName.jsl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(opposite|opposite-add)\b</string>
					<key>name</key>
					<string>keyword.control.jsl</string>
				</dict>
			</array>
		</dict>
		<key>modifiersNotInEntity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(query)\b</string>
					<key>name</key>
					<string>storage.type.function.jsl</string>
				</dict>
			</array>
		</dict>
		<key>lambda-expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>=></string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>storage.type.function.arrow.jsl</string>
							</dict>
						</dict>	
						<key>name</key>
						<string>meta.meta.lambdaExpressionBody.in.jsl.jsl</string>
						<key>end</key>
						<string>(?=;)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#expressions</string>
							</dict>
						</array>
				</dict>
			</array>
		</dict>
		<key>terminal-signal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.control.jsl</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:(0[0-7]+)L?)</string>
					<key>name</key>
					<string>constans.numberic.octal.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(\\d+\\.\\d*(e[\\-\\+]?\\d+)?))(?=[^a-zA-Z_])</string>
					<key>name</key>
					<string>constans.numberic.float.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[^0-9a-zA-Z_])(?i:(\\.\\d+(e[\\-\\+]?\\d+)?))</string>
					<key>name</key>
					<string>constans.numberic.float.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(\\d+e[\\-\\+]?\\d+))</string>
					<key>name</key>
					<string>constans.numberic.float.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:([1-9]+[0-9]*|0)L)</string>
					<key>name</key>
					<string>constant.numeric.integer.long.decimal.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([1-9]+[0-9]*|0)</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.jsl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>end</key>
					<string>\"</string>
					<key>name</key>
					<string>string.quoted.double.states</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\\b</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+\#(\w+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.enummember</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>enum-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(enum)\s+(\w+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.enum.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.entity.jsl</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.enum.end.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#enum-block-body</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>enum-block-body</key>
		<dict>
			<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.enum.begin.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.enitity.body.java</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>(\w+)\s*=</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>variable.other.enummember</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>keyword.operator.assignment.jsl</string>
										</dict>
									</dict>									
								</dict>
								<dict>
									<key>include</key>
									<string>#literals</string>				
								</dict>
								<dict>
									<key>include</key>
									<string>#terminal-signal</string>				
								</dict>
							</array>
					</dict>
				</array>
		</dict>
		<key>entity-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(entity)(\s+abstract)?\s+(\w+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.entityName.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.entity.jsl</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.entity.end.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>extends</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.extends.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={)</string>
							<key>name</key>
							<string>meta.definition.entity.inherited.classes.end.jsl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#entity-inheretend</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
								<key>beginCaptures</key>
								<dict>
									<key>0</key>
									<dict>
										<key>name</key>
										<string>punctuation.section.entity.begin.jsl</string>
									</dict>
								</dict>
								<key>end</key>
								<string>(?=})</string>
								<key>name</key>
								<string>meta.enitity.body.java</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#entity-body</string>
									</dict>
								</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>entity-body</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifiersInEntity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lambda-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal-signal</string>				
				</dict>
			</array>
		</dict>
		<key>expressions</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lambda-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal-signal</string>				
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>				
				</dict>
			</array>
		</dict>
		<key>entity-inheretend</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\w+)\s*\,</string>
					<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>entity.other.inherited-class.inheritendEntityName.jsl</string>
							</dict>
						</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\w+</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.inheritendEntityName.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?={)</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.jsl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>/\*\*/</string>
					<key>name</key>
					<string>comment.block.empty.jsl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.jsl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.jsl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jsl</string>
	<key>uuid</key>
	<string>9E6E7290-F2E8-4D58-97E2-08CBBB3EB7E8</string>
</dict>
</plist>
